<template>
  <modal title="README.md" @close="emit('toggle-about-modal')">
    <!--Generated by throwing the README.md into https://markdowntohtml.com-->
    <h1 id="zelda-timelines">Zelda timelines</h1>
    <p>
      The Legend of Zelda franchise consists of various games. Each game can be enjoyed as a
      standalone experience. However those who played multiple titles might notice the games
      referencing each other from obvious to subtle ways. Fans that find satisfaction in
      contemplating and theorizing about Zelda lore and mythos came up with various arrangements
      that place the games in a chronology. This site is an interactive collection of Zelda
      timelines that provides an easy way to visualize, absorb and compare the timelines all in one
      place. Perhaps new conclusions can be made?
    </p>
    <h2 id="credits">Credits</h2>
    <h3 id="supported-timelines">Supported timelines</h3>
    <ul>
      <li>
        The official one [<a href="https://www.zelda.com/about/">NA site</a>] [<a
          href="https://www.nintendo.com/jp/character/zelda/history/index.html"
          >JP site</a
        >]
      </li>
      <li>
        Triforce Johnson&#39;s of Empire Arcadia [<a href="https://youtu.be/HPnvAt9bvAs">video</a>]
        [<a href="https://www.youtube.com/playlist?list=PLYYZg45BvGCMoNCbPlhfV0296IOfrBUVz"
          >playlist</a
        >]
      </li>
      <li>
        LoruleanHistorian/Instrutilus/Zelda Lore&#39;s [<a
          href="https://www.youtube.com/watch?v=7GAqIqYzqGQ"
          >video</a
        >]
      </li>
      <li>
        Frank Moussette&#39;s of Geekery Collective [<a
          href="https://www.youtube.com/playlist?list=PLdwzMC_Gye94WEBMT0--HneBOJXJaM1Mg"
          >playlist</a
        >]
      </li>
      <li>
        AbsurdZeldaTheories aka Bird Keeper Toby&#39;s [<a
          href="https://www.youtube.com/watch?v=rPrqd6682gE"
          >video</a
        >]
      </li>
    </ul>
    <p>If I come across other timeline theories I&#39;ll be interested in adding them too.</p>
    <h3 id="game-descriptions">Game descriptions</h3>
    <p>
      Descriptions of the games are sourced from
      <a href="https://niwanetwork.org/wiki/Main_Page">NIWA Network</a> and are licensed under the
      <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/">CC BY-NC-SA 3.0</a> license. I
      shortened some of their descriptions. Other descriptions were paraphrased from Nintendo
      Japan&#39;s
      <a href="https://www.nintendo.com/jp/character/zelda/history/index.html">Zelda Portal</a>.
    </p>
    <h3 id="icon-allowance">Icon allowance</h3>
    <p>
      Joshua Lindquist of <a href="https://zeldauniverse.net/">Zelda Universe</a> granted the
      permission of using the game icons.
    </p>
    <h3 id="box-art">Box art</h3>
    <p>
      The box art images used in this project are the property of Nintendo. They are used here for
      illustrative purposes and to enhance the user experience. All rights, including copyright and
      trademarks, are owned by Nintendo. No infringement is intended.
    </p>
    <ul>
      <li>Found at <a href="https://www.thecoverproject.net/index.php">The Cover Project</a>.</li>
    </ul>
    <h3 id="fonts">Fonts</h3>
    <ul>
      <li>Found at <a href="https://zeldauniverse.net/media/fonts/">Zelda Universe</a></li>
    </ul>
    <h2 id="development">Development</h2>
    <p><a href="https://github.com/shawnyama/zelda-timelines">Source code repository</a></p>
    <h3 id="tech-stack">Tech Stack</h3>
    <ul>
      <li><a href="https://yarnpkg.com/getting-started/install">Yarn</a></li>
      <li><a href="https://nodejs.org/en/download/current/">NodeJS 18</a></li>
      <li><a href="https://vuejs.org/guide/quick-start.html">Vue 3</a></li>
    </ul>
    <p>
      Timeline graph rendered using
      <a href="https://github.com/dword-design/vue-mermaid-string">vue-mermaid-string</a> which is
      based on <a href="https://mermaid.js.org/">Mermaid</a>
    </p>
    <h3 id="run">Run</h3>
    <p>Clone the repository then</p>
    <pre><code>yarn <span class="hljs-keyword">install</span>
    yarn dev
    </code></pre>
    <p>© 2024 <a href="https://shawnyama.ca/">Shawn Yama</a></p>
  </modal>
</template>

<script setup lang="ts">
import Modal from './widgets/Modal.vue'

const emit = defineEmits(['toggle-about-modal'])
</script>

<style scoped>
h1,
h2,
h3 {
  color: var(--dark-green);
}

h2 {
  border-bottom: 1px solid var(--dark-green);
}

h2,
h3 {
  text-transform: lowercase;
}

h3 {
  margin-left: 0.5rem;
}

h1 + p {
  padding: 0;
  padding-bottom: 0.25rem;
}

p,
pre {
  padding: 0 0.5rem;
}

p,
ul,
pre {
  padding-bottom: 0.25rem;
}
</style>
